"""Add models and model_scores for PassMark

Revision ID: 31285ab19280
Revises: b666fb9e8aad
Create Date: 2026-05-30 00:11:38.681459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31285ab19280'
down_revision: Union[str, Sequence[str], None] = 'b666fb9e8aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_scores_updated_at'), 'model_scores', ['updated_at'], unique=False)
    
    # Добавление столбца model_id в таблицу components через batch-режим
    with op.batch_alter_table('components') as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_components_model_id', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components') as batch_op:
        batch_op.drop_constraint('fk_components_model_id', type_='foreignkey')
        batch_op.drop_column('model_id')
    
    op.drop_index(op.f('ix_model_scores_updated_at'), table_name='model_scores')
    op.drop_table('model_scores')
    op.drop_table('models')
    # ### end Alembic commands ###
