"""Add models and model_scores

Revision ID: 340c0d6fde39
Revises: 31285ab19280
Create Date: 2026-05-30 00:17:10.059335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340c0d6fde39'
down_revision: Union[str, Sequence[str], None] = '31285ab19280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'components', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'components', type_='foreignkey')
    # ### end Alembic commands ###
