"""Initial schema with separate component tables

Revision ID: b072a5823e49
Revises: 
Create Date: 2026-05-25 15:51:06.967251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b072a5823e49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('benefit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('benefit', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_history_timestamp'), 'benefit_history', ['timestamp'], unique=False)
    op.create_table('case_components',
    sa.Column('form_factor_support', sa.JSON(), nullable=True),
    sa.Column('max_gpu_length_mm', sa.Integer(), nullable=True),
    sa.Column('max_cooler_height_mm', sa.Integer(), nullable=True),
    sa.Column('drive_bays_35', sa.Integer(), nullable=True),
    sa.Column('drive_bays_25', sa.Integer(), nullable=True),
    sa.Column('included_fans', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('column_spec_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('spec_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spec_type_id'], ['spec_types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooler_components',
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('tdp_watts', sa.Integer(), nullable=True),
    sa.Column('fan_size_mm', sa.Integer(), nullable=True),
    sa.Column('radiator_size_mm', sa.String(length=30), nullable=True),
    sa.Column('socket_compatibility', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpu_components',
    sa.Column('socket', sa.String(length=50), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('base_clock_ghz', sa.Float(), nullable=True),
    sa.Column('turbo_clock_ghz', sa.Float(), nullable=True),
    sa.Column('tdp_watts', sa.Integer(), nullable=True),
    sa.Column('integrated_graphics', sa.String(length=100), nullable=True),
    sa.Column('cache_l3_mb', sa.Integer(), nullable=True),
    sa.Column('node_nm', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpu_components',
    sa.Column('chipset', sa.String(length=50), nullable=True),
    sa.Column('vram_gb', sa.Float(), nullable=True),
    sa.Column('vram_type', sa.String(length=20), nullable=True),
    sa.Column('bus_width_bit', sa.Integer(), nullable=True),
    sa.Column('power_connectors', sa.String(length=50), nullable=True),
    sa.Column('tdp_watts', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hdd_components',
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('cache_mb', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motherboard_components',
    sa.Column('socket', sa.String(length=50), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('chipset', sa.String(length=50), nullable=True),
    sa.Column('ram_slots', sa.Integer(), nullable=True),
    sa.Column('ram_type', sa.String(length=20), nullable=True),
    sa.Column('max_ram_gb', sa.Integer(), nullable=True),
    sa.Column('m2_slots', sa.Integer(), nullable=True),
    sa.Column('pcie_x16_slots', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('psu_components',
    sa.Column('wattage', sa.Integer(), nullable=True),
    sa.Column('efficiency_rating', sa.String(length=20), nullable=True),
    sa.Column('modular', sa.String(length=20), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ram_components',
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('frequency_mhz', sa.Integer(), nullable=True),
    sa.Column('latency_cl', sa.String(length=10), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_history_timestamp'), 'score_history', ['timestamp'], unique=False)
    op.create_table('ssd_components',
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=20), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('read_speed_mb', sa.Integer(), nullable=True),
    sa.Column('write_speed_mb', sa.Integer(), nullable=True),
    sa.Column('tbw', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssd_components')
    op.drop_index(op.f('ix_score_history_timestamp'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_table('ram_components')
    op.drop_table('psu_components')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('motherboard_components')
    op.drop_table('hdd_components')
    op.drop_table('gpu_components')
    op.drop_table('cpu_components')
    op.drop_table('cooler_components')
    op.drop_table('column_spec_mapping')
    op.drop_table('case_components')
    op.drop_index(op.f('ix_benefit_history_timestamp'), table_name='benefit_history')
    op.drop_table('benefit_history')
    op.drop_table('spec_types')
    op.drop_table('component_types')
    # ### end Alembic commands ###
