"""Initial schema

Revision ID: b666fb9e8aad
Revises: b072a5823e49
Create Date: 2026-05-25 16:09:40.145132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b666fb9e8aad'
down_revision: Union[str, Sequence[str], None] = 'b072a5823e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_components',
    sa.Column('storage_type', sa.String(length=10), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=20), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('read_speed_mb', sa.Integer(), nullable=True),
    sa.Column('write_speed_mb', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('cache_mb', sa.Integer(), nullable=True),
    sa.Column('tbw', sa.Integer(), nullable=True),
    sa.Column('nand_type', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dns_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hdd_components')
    op.drop_table('ssd_components')
    op.add_column('cooler_components', sa.Column('cooler_type', sa.String(length=20), nullable=True))
    op.drop_column('cooler_components', 'type')
    op.add_column('ram_components', sa.Column('memory_type', sa.String(length=10), nullable=True))
    op.drop_column('ram_components', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ram_components', sa.Column('type', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('ram_components', 'memory_type')
    op.add_column('cooler_components', sa.Column('type', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('cooler_components', 'cooler_type')
    op.create_table('ssd_components',
    sa.Column('capacity_gb', sa.INTEGER(), nullable=True),
    sa.Column('interface', sa.VARCHAR(length=20), nullable=True),
    sa.Column('form_factor', sa.VARCHAR(length=20), nullable=True),
    sa.Column('read_speed_mb', sa.INTEGER(), nullable=True),
    sa.Column('write_speed_mb', sa.INTEGER(), nullable=True),
    sa.Column('tbw', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('dns_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hdd_components',
    sa.Column('capacity_gb', sa.INTEGER(), nullable=True),
    sa.Column('rpm', sa.INTEGER(), nullable=True),
    sa.Column('form_factor', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cache_mb', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('dns_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('storage_components')
    # ### end Alembic commands ###
